- name: Install personal tools
  hosts: localhost

  tasks:

    - name: Fundamental tools
      ansible.builtin.include_tasks:
        file: tasks/fundamental_tools.yml

    - name: Dev tools
      ansible.builtin.include_tasks:
        file: tasks/dev_tools.yml

    - name: Languages
      ansible.builtin.include_tasks:
        file: tasks/languages.yml