- name: Install Browsers
  ansible.builtin.package:
    name:
      - brave-bin
      - firefox
    state: present
  become:true

- name: Install Discord and Spotify
  ansible.builtin.package:
    name:
      - discord-canary
      - spotify-launcher
    state: present
  become: true

- name: Install PDF signer/reader
  ansible.builtin.package:
    name:
      - stirling-pdf-desktop
    state: present
  become: true

- name: Install Screen Recorder and stream tools
  ansible.builtin.package:
    name:
      - obs-studio-browser
      - gpu-screen-recorder-ui
      - ffmpeg
      - mangohud-git
      - lib32-mangohud-git
      - kdotool-bin
    state: present
  become: true

- name: Install Media Viewers
  ansible.builtin.package:
    name:
      - qimgv-git
      - fooyin
    state: present
  become: true

- name: Install VPN Tools
  ansible.builtin.package:
    name:
      - wireguard-tools
    state: present
  become: true
