pulse.rules = [
    {
        matches = [
            # Firefox & Firefox-based Browsers
            { application.process.binary = "firefox" }
            { application.process.binary = "firefox-bin" }
            { application.process.binary = "tor-browser" }

            # Google Chrome & Chromium
            { application.process.binary = "chrome" }
            { application.process.binary = "google-chrome" }
            { application.process.binary = "google-chrome-stable" }
            { application.process.binary = "chromium" }
            { application.process.binary = "chromium-browser" }

            # Brave
            { application.process.binary = "brave" }
            { application.process.binary = "brave-browser" }
            { application.process.binary = "brave-browser-beta" }
            { application.process.binary = "brave-browser-nightly" }

            # Vivaldi & Opera
            { application.process.binary = "vivaldi" }
            { application.process.binary = "vivaldi-bin" }
            { application.process.binary = "vivaldi-snapshot" }

        ]
        actions = {
            update-props = {
                target.object = "BrowserSink"
            }
        }
    }
]
