[mgr]
show_hidden = true
sort_dir_first = true
show_symlink = true
mouse_events = ["scroll", "touch", "click"]

[manager]
linemode="git"

[opener]
edit = [
    {run="vim %s", orphan=false, block=true,for="unix"}
]

open_dir = [
    {run="zed %s", orphan=true, block=false, for="unix"}
]

open_vid = [
    {run="vlc %s", orphan=true, block=false, for="unix"}
]

open_img = [
    {run="qimgv %s", orphan=true, block=false, for="unix"}
]

open_audio = [
    {run="fooyin %s", orphan=true, block=false, for="unix"}
]

[open]
rules = [
    {mime="folder/*", use="open_dir"},
    {mime="text/*", use="edit"},
    {mime="video/*", use="open_vid"},
    {mime="image/*", use="open_img"},
    {mime="audio/*", use="open_audio"},
]

[plugin]

[[plugin.prepend_fetchers]]
id="git"
url="*"
run="git"
group="git"

[[plugin.prepend_fetchers]]
id="git"
url="/*"
run="git"
group="git"

[[plugin.prepend_previewers]]

# Markdown Preview
url = "*.md"
run = 'piper -- CLICOLOR_FORCE=1 glow -w=$w -s=dark "$1"'
